// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/**
 * @dev Defines minting functions
 */
interface IMinter {
  /**
   * @dev Creates a new token for `to`. Its token ID will be automatically
   * assigned (and available on the emitted {IERC721-Transfer} event), and the token
   * URI autogenerated based on the base URI passed at construction.
   */
  function mint(address to) external;
}
